spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/demo?useSSL=false&logging=DEBUG
    username: user
    password: password
    pool:
      max-size: 10
      initial-size: 5
      max-idle-time: 30s
      validation-query: SELECT 1
  #  datasource:
#    url: jdbc:mysql://mysql-container:3306/demo?useSSL=false
#    username: user
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: INFO
    io.r2dbc.mysql: DEBUG
    io.r2dbc.spi: OFF
    reactor.netty: OFF
    javax.management.remote.rmi: OFF
    sun.rmi.transport.tcp: OFF
    sun.rmi.loader: OFF
    io.netty: OFF
